fix(#27): Fix debian changelog generation, adjust debian workflow, add better ignores to docker workflow, allow any cache to work, downgrade to ubuntu-22.04 so it matches docker

diff --git a/.github/workflows/build-common.yml b/.github/workflows/build-common.yml
--- a/.github/workflows/build-common.yml
+++ b/.github/workflows/build-common.yml
@@ -15,7 +15,8 @@ on:
 jobs:
   build:
     name: Build
-    runs-on: ubuntu-latest
+    # if you change this, you need to update build.yml, docker.yml, and debian.yml, and possibly Dockerfile
+    runs-on: ubuntu-22.04
 
     steps:
       - uses: actions/checkout@v4
@@ -36,7 +37,9 @@ jobs:
         uses: Swatinem/rust-cache@v2
         with:
           key: ${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}-${{ hashFiles('**/Cargo.toml') }}
-          shared-key: ${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
+          shared-key: |
+            ${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
+            ${{ runner.os }}
           workspaces: |
             .
           cache-targets: true
@@ -55,11 +58,16 @@ jobs:
           echo "tag=$(git describe --tags --always)" >> $GITHUB_OUTPUT
 
       - name: Build
+        id: build
         run: |
           export BUILD_TIMESTAMP=${{ steps.get_timestamp.outputs.timestamp }}
           export GIT_SHA=${{ steps.get_git_info.outputs.sha }}
           export GIT_TAG=${{ steps.get_git_info.outputs.tag }}
-          RUSTFLAGS="-C target-cpu=native" cargo build --release
+          RUSTFLAGS="-C target-cpu=native" cargo build --release || {
+            echo "Build failed, clearing cache and retrying..."
+            cargo clean
+            RUSTFLAGS="-C target-cpu=native" cargo build --release
+          }
           mkdir -p artifacts
           cp target/release/snapshot-gossip-client artifacts/
           cp example-config.toml artifacts/
